// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function Greet(arg1:string):Promise<string>;

export function ParseApk(arg1:string):Promise<model.Feature>;

export function ParseIpa(arg1:string):Promise<model.Feature>;

export function SaveToZip(arg1:string):Promise<void>;

export function Test():Promise<model.EventData>;
