// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['parser']['App']['Greet'](arg1);
}

export function ParseApk(arg1) {
  return window['go']['parser']['App']['ParseApk'](arg1);
}

export function ParseIpa(arg1) {
  return window['go']['parser']['App']['ParseIpa'](arg1);
}

export function SaveToZip(arg1) {
  return window['go']['parser']['App']['SaveToZip'](arg1);
}

export function Test() {
  return window['go']['parser']['App']['Test']();
}
